// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'createButton': string;
  'header': string;
  'numberButton': string;
  'numberButtons': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
