// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'gameName': string;
  'playersName': string;
  'playersNames': string;
  'rightPart': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
