// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'greeting': string;
  'root': string;
  'row': string;
  'title': string;
  'topBar': string;
}
export const cssExports: CssExports;
export default cssExports;
